#!/bin/sh
source $HOME/.nvm/nvm.sh
# Get the name of the current folder.
raw_folder=${PWD##*/}
# Replace hypehens with underscores.
project_folder=${raw_folder//-/_}

# Create a virtual environment and get things installed.
python3 -m venv --prompt . .venv
.venv/bin/pip install -U pip setuptools wheel
source .venv/bin/activate
python -m pip install pip-tools
pip-compile --resolver=backtracking requirements/requirements.in
python -m pip install -r requirements/requirements.txt

cp example.env .env

# Name the Django project with the same name as our base folder.
django-admin startproject $project_folder .

# Create a "core" app.
cd $project_folder
../manage.py startapp core
cd ..

# Delete an extraneous file.
rm $project_folder/core/apps.py

# Add some new files and a folder.
cp self-destruct/admin.py $project_folder/core/
cp self-destruct/models.py $project_folder/core/
cp self-destruct/views.py $project_folder/core/
cp self-destruct/tests.py $project_folder/core/
cp self-destruct/urls.py $project_folder/
mkdir -p $project_folder/core/templates/
cp self-destruct/placeholder.html $project_folder/core/templates/
mkdir -p static/

# Set up pre-commit.
pre-commit install

# Install JS stuff.
nvm install
npm i -D stylelint-config-standard stylelint npm-run-all eslint

next_steps="
\n\n
---\n\n
🎉 **Next steps:**\n\n
Visit https://github.com/piepworks/django-starter#next-steps\n\n
Follow those instructions, replacing \`[project_folder]\` with \`${project_folder}\`.
\n\n
---\n\n
"

if command -v gum &> /dev/null
then
  echo $next_steps | gum format
else
  echo $next_steps
fi

# Delete our starter stuff?
# rm -rf self-destruct/
