#!/bin/bash

# This is for testing the Blaze.horse — Django Starter Kit itself.

echo ""
read -p "Create test build folder (./.test_project/) and run automated tests? (Y/N) " yn
case $yn in
    [Yy])
        mkdir .test_project
        cd .test_project
        python3 -m venv --prompt . .venv
        .venv/bin/pip install -U pip setuptools wheel
        .venv/bin/python -m pip install Django uv
        .venv/bin/django-admin startproject --template=../ test_project .
        .venv/bin/uv sync --no-dev --locked
        .venv/bin/python manage.py makemigrations
        mv dev/0002_adjust_timezone_migration.py core/migrations/0002_adjust_timezone_migration.py
        .venv/bin/python manage.py migrate --noinput
        .venv/bin/python manage.py collectstatic --noinput
        source $HOME/.nvm/nvm.sh
        nvm install
        npm install
        npm run build
        .venv/bin/pytest
        npx playwright install --with-deps

        # Run Playwright tests with a new user
        printf "CREATE_USER=True\nPLAYWRIGHT_USERNAME=tester@example.com\nPLAYWRIGHT_PASSWORD=tester_password" > ../e2e/playwright.env
        npx playwright test

        read -p "Delete test build folder (./.test_project/)? (Y/N) " yn2
        case $yn2 in
            [Yy])
                cd .. && rm -rf .test_project
                ;;
            *)
                echo ""
                echo "To delete test build folder later, run 'dev/test-build-reset'"
                ;;
        esac

        ;;
    *)
        echo ""
        echo "Okie doke"
        ;;
esac
