#!/bin/sh

# Get the name of the current folder.
raw_folder=${PWD##*/}
# Replace hypehens with underscores.
project_folder=${raw_folder//-/_}

# Create a virtual environment and get things installed.
python3 -m venv --prompt . .venv
.venv/bin/pip install -U pip setuptools wheel
source .venv/bin/activate
python -m pip install pip-tools
pip-compile --resolver=backtracking
python -m pip install -r requirements.txt

touch .env

# Name the Django project with the same name as our base folder.
django-admin startproject $project_folder .

# Create a "core" app.
cd $project_folder
../manage.py startapp core
cd ..

# Delete an extraneous file.
rm $project_folder/core/apps.py

# Add some new files.
cp self-destruct/models.py $project_folder/core/
cp self-destruct/admin.py $project_folder/core/

python manage.py makemigrations
python manage.py migrate
python manage.py createsuperuser

# Set up pre-commit
pre-commit install

if command -v gum &> /dev/null
then
  cat self-destruct/next-steps.md | gum format
else
  cat self-destruct/next-steps.md
fi

# Delete our starter stuff?
# rm -rf self-destruct/
