#!/bin/sh

# Get the name of the current folder.
raw_folder=${PWD##*/}
# Replace hypehens with underscores.
project_folder=${raw_folder//-/_}

# Create a virtual environment and get things installed.
python3 -m venv --prompt . .venv
.venv/bin/pip install -U pip setuptools wheel
source .venv/bin/activate
python -m pip install pip-tools
pip-compile
python -m pip install -r requirements.txt

# Name the Django project with the same name as our base folder.
django-admin startproject $project_folder .

# Create a "core" app.
cd $project_folder
../manage.py startapp core
